name: cdk

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cdk deploy
        uses: 1davidmichael/aws-cdk-github-actions@fix_args
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          working_dir: 'infra'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      - name: Build Hexo Site
        uses: actions/setup-node@v1
      - run: npm install -g hexo-cli
      - run: cd blog && npm install
      - run: cd blog && hexo generate
      - run: cd blog/public && aws s3 sync --acl public-read . s3://david-michael-blog-bucket