name: cdk

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CDK_DEPLOY_REGION }}

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'deploy --require-approval never'
          working_dir: 'infra'
          actions_comment: false
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.CDK_DEPLOY_ACCOUNT }}
      - name: Build Hexo Site
        uses: actions/setup-node@v1

      - run: npm install -g hexo-cli
      - run: cd blog && npm install
      - run: cd blog && hexo generate
      - run: cd blog/public && aws s3 sync --delete --acl public-read . s3://david-michael-blog-bucket